name: 'Setup Environment'
description: 'Setup common environment'
runs:
  using: 'composite'
  steps:
    - run: git config advice.detachedHead false
      shell: bash
    - name: Comment out tools not available in mise
      run: sed -i 's/^spotbugs /#spotbugs /' .tool-versions
      shell: bash
    - name: Install mise & tools
      uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
      with:
        install: true
